package reprodutor;


import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DAM2 (Álvaro Cordero Fernández)
 */
public class SoundReproductor extends javax.swing.JFrame {

    Reproductor rep = new Reproductor(); // Clase que controlará el audio
    File file;
    int posX;
    int posY;
    boolean isFileCorrect = false;
    public static boolean isPlaying = false;

    /**
     * Creates new form ReproductorSonido
     */
    public SoundReproductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bSelectFile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFileShown = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        progressMusicDuration = new javax.swing.JSlider();
        bPlay = new javax.swing.JButton();
        bStop = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sVolume = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reproductor de audio");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(650, 420));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(28, 33, 40));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(650, 410));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 410));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 410));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        bExit.setBackground(new java.awt.Color(77, 79, 81));
        bExit.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        bExit.setForeground(new java.awt.Color(255, 255, 255));
        bExit.setText("X");
        bExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bExit.setBorderPainted(false);
        bExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bExit.setHideActionText(true);
        bExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bExitMouseExited(evt);
            }
        });
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));
        jPanel2.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select a wav file");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bSelectFile.setBackground(new java.awt.Color(51, 51, 51));
        bSelectFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bSelectFile.setForeground(new java.awt.Color(255, 255, 255));
        bSelectFile.setText("Select");
        bSelectFile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSelectFile.setBorderPainted(false);
        bSelectFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSelectFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSelectFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSelectFileMouseExited(evt);
            }
        });
        bSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelectFileActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("File:");

        jFileShown.setBackground(new java.awt.Color(0, 153, 153));
        jFileShown.setFont(new java.awt.Font("Alef", 1, 18)); // NOI18N
        jFileShown.setForeground(new java.awt.Color(255, 255, 255));
        jFileShown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFileShown.setText("Nothing yet");
        jFileShown.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jFileShown.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jFileShown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jFileShown, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bSelectFile)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        progressMusicDuration.setBackground(new java.awt.Color(0, 102, 102));
        progressMusicDuration.setForeground(new java.awt.Color(0, 153, 153));
        progressMusicDuration.setValue(0);
        progressMusicDuration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        progressMusicDuration.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        progressMusicDuration.setEnabled(false);
        progressMusicDuration.setOpaque(true);

        bPlay.setBackground(new java.awt.Color(51, 51, 51));
        bPlay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bPlay.setForeground(new java.awt.Color(255, 255, 255));
        bPlay.setText("Play");
        bPlay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bPlay.setBorderPainted(false);
        bPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bPlay.setEnabled(false);
        bPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bPlayMouseExited(evt);
            }
        });
        bPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlayActionPerformed(evt);
            }
        });

        bStop.setBackground(new java.awt.Color(51, 51, 51));
        bStop.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bStop.setForeground(new java.awt.Color(255, 255, 255));
        bStop.setText("Stop");
        bStop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bStop.setBorderPainted(false);
        bStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bStop.setEnabled(false);
        bStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bStopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bStopMouseExited(evt);
            }
        });
        bStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStopActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Volume:");

        sVolume.setBackground(new java.awt.Color(0, 102, 102));
        sVolume.setForeground(new java.awt.Color(0, 153, 153));
        sVolume.setMaximum(6);
        sVolume.setMinimum(-80);
        sVolume.setToolTipText("");
        sVolume.setValue(-24);
        sVolume.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sVolume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sVolume.setEnabled(false);
        sVolume.setOpaque(true);
        sVolume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sVolumeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressMusicDuration, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bStop, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPlay)
                    .addComponent(bStop))
                .addGap(8, 8, 8)
                .addComponent(progressMusicDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cambiamos el color del boton por uno rojo
     *
     * @param evt
     */
    private void bExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExitMouseEntered
        bExit.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_bExitMouseEntered

    /**
     * Dejamos el color del boton como estaba
     *
     * @param evt
     */
    private void bExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExitMouseExited
        bExit.setBackground(new Color(77, 79, 81));
    }//GEN-LAST:event_bExitMouseExited

    /**
     * Cierra la venatna
     *
     * @param evt
     */
    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bSelectFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSelectFileMouseEntered
        bSelectFile.setBackground(new Color(0, 120, 215));
    }//GEN-LAST:event_bSelectFileMouseEntered

    private void bSelectFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSelectFileMouseExited
        bSelectFile.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_bSelectFileMouseExited

    /**
     * Se muestra un JFileChooser para seleccionar el audio Si es correcto el
 file se muestra de verde, sino de rojo
     *
     * @param evt
     */
    private void bSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelectFileActionPerformed

        // Si la musica se reproduce se para
        if (isPlaying) {
            rep.pararMusica();
            isPlaying = false;
        }

        // Se crea un JFileChooser para seleccionar el file
        JFileChooser seleccionadorArchivos = new JFileChooser();

        int respuesta = seleccionadorArchivos.showOpenDialog(this);

        if (respuesta == JFileChooser.APPROVE_OPTION) {
            file = seleccionadorArchivos.getSelectedFile();
            System.out.println("File: " + file);

            if (file.getName().endsWith(".wav")) {
                jFileShown.setForeground(Color.GREEN);
                isFileCorrect = true;
                
                
                // Ahora se puede interactuar con los mandos de control
                bPlay.setEnabled(true);  // Reproducir la musica
                bStop.setEnabled(true);      // Parar la musica 
                sVolume.setEnabled(true);     // Cambiar el volumen
                
                

            } else {
                jFileShown.setForeground(Color.RED);
                isFileCorrect = false;
            }

            jFileShown.setText(file.getName());
        }
    }//GEN-LAST:event_bSelectFileActionPerformed

    /**
     * Cambia la ventana de posicion
     *
     * @param evt
     */
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int nuevoX = evt.getXOnScreen();
        int nuevoY = evt.getYOnScreen();
        setLocation(nuevoX - posX, nuevoY - posY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void bPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPlayMouseEntered
        bPlay.setBackground(new Color(0, 120, 215));
    }//GEN-LAST:event_bPlayMouseEntered

    private void bPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPlayMouseExited
        bPlay.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_bPlayMouseExited

    private void bPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlayActionPerformed
        try {

            if (isFileCorrect && ! isPlaying) {

                // Cambiamos el nuevo file que se va a reproducir
                rep.cambiarArchivo(file);
                //Ponemos el volumen bajo
                sVolume.setValue(-24);
                rep.cambiarVolumen(-24);

                // Settea el slider con las nuevas proporciones
                progressMusicDuration.setMaximum(rep.getDuracion());
                System.out.println("Duration of " + rep.getDuracion() + " seconds");
                rep.setSlider(progressMusicDuration);


                // Reproduce la musica
                rep.empezarMusica();
                isPlaying = true;
            }

        } catch (Exception e) {

            // Ahora  NO se puede interactuar con los mandos
            bPlay.setEnabled(false);  // Reproducir la musica
            bStop.setEnabled(false);      // Parar la musica 
            sVolume.setEnabled(false);     // Cambiar el volumen
            System.out.println("\033[91mERROR: \033[94m" + e.getLocalizedMessage());
        }

    }//GEN-LAST:event_bPlayActionPerformed

    private void bStopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStopMouseEntered
        bStop.setBackground(new Color(0, 120, 215));
    }//GEN-LAST:event_bStopMouseEntered

    private void bStopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStopMouseExited
        bStop.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_bStopMouseExited

    private void bStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStopActionPerformed
        if (isPlaying) {
            rep.pararMusica();
            isPlaying = false;
        }
    }//GEN-LAST:event_bStopActionPerformed

    /**
     * Coge un nuevo valor de voluemn para el sonido
     *
     * @param evt
     */
    private void sVolumeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVolumeMouseReleased
        System.out.println("New volume: " + sVolume.getValue());
        rep.cambiarVolumen(sVolume.getValue());
    }//GEN-LAST:event_sVolumeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoundReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SoundReproductor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JButton bPlay;
    private javax.swing.JButton bSelectFile;
    private javax.swing.JButton bStop;
    private javax.swing.JLabel jFileShown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSlider progressMusicDuration;
    private javax.swing.JSlider sVolume;
    // End of variables declaration//GEN-END:variables
}
